# autogenerated by docgen
# source: /home/runner/work/fusion/fusion/fusion/src/fusion/js/jssets.nim
# rdoccmd: 
import "/home/runner/work/fusion/fusion/fusion/htmldocs/nimcache/runnableExamples/jssets_examples_1.nim"
