#[
autogenerated by docgen
loc: /home/runner/work/fusion/fusion/fusion/src/fusion/js/jssets.nim(36, 1)
rdoccmd: 
]#
import std/assertions
import "/home/runner/work/fusion/fusion/fusion/src/fusion/js/jssets.nim"
{.line: ("/home/runner/work/fusion/fusion/fusion/src/fusion/js/jssets.nim", 36, 1).}:
  import std/jsffi
  if defined(fusionJsSetTests):
    let a: JsSet = newJsSet([1.toJs, 2.toJs, 3.toJs, 4.toJs])
    let b: JsSet = newJsSet([1.0.toJs, 2.0.toJs, 3.0.toJs])
    doAssert a.len == 4
    doAssert b.len == 3
    doAssert a.toString() == @["1".cstring, "2", "3", "4"]
    doAssert b.toString() == @["1".cstring, "2", "3"]
    a.clear()
    b.clear()
    let d: JsSet = newJsSet([1.toJs, 2.toJs, 3.toJs])
    doAssert d.len == 3
    d.add(4.toJs)
    d.delete(2.toJs)
    doAssert 3.toJs in d
    doAssert "3".cstring.toJs notin d
    doAssert d.contains 1.toJs
    doAssert $d == """@["1", "3", "4"]"""

