#[
autogenerated by docgen
loc: /home/runner/work/fusion/fusion/fusion/src/fusion/js/jsxmlserializer.nim(16, 1)
rdoccmd: 
]#
import std/assertions
import "/home/runner/work/fusion/fusion/fusion/src/fusion/js/jsxmlserializer.nim"
{.line: ("/home/runner/work/fusion/fusion/fusion/src/fusion/js/jsxmlserializer.nim", 16, 1).}:
  from std/dom import document
  if defined(fusionJsXMLSerializerTests):
    let cerealizer: XMLSerializer = newXMLSerializer()
    echo cerealizer.serializeToString(node = document)

