# autogenerated by docgen
# source: /home/runner/work/fusion/fusion/fusion/src/fusion/js/jsxmlhttprequest.nim
# rdoccmd: 
import "/home/runner/work/fusion/fusion/fusion/htmldocs/nimcache/runnableExamples/jsxmlhttprequest_examples_1.nim"
