# autogenerated by docgen
# source: /home/runner/work/fusion/fusion/fusion/src/fusion/js/jsxmlserializer.nim
# rdoccmd: 
import "/home/runner/work/fusion/fusion/fusion/htmldocs/nimcache/runnableExamples/jsxmlserializer_examples_1.nim"
